spring:
  sql.init.mode: never
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    jpa:
      ddl-auto: create-drop
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      defer-datasource-initialization: true
      show-sql: true
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
