spring:
  profiles:
    active: local
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    jpa:
      ddl-auto: validate
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      defer-datasource-initialization: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
